# docker-compose.yml
#
# Single-node test compose file.
# Each container gets 20 vCPU and 20 GiB RAM limits.

version: "3.9"

services:
  node1:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.1   # ← after you push
    container_name: gensyn-test1

    environment:
      P2P_PORT: 38331
      CPU_ONLY: "1"          # force the CPU branch

    # mount only keys
    volumes:
    # JSON
      - "./data/node1/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"
    # swarm.pem
      - "./identities/node1/swarm.pem:/opt/rl-swarm/swarm.pem"

    ports:
      - "38331:38331"
      - "13001:8000"         # UI (optional)

    deploy:
      resources:
        limits:
          cpus: "20.0"
          memory: 20g

    cpuset: "0-19"
    
    # restart: on-failure

    # optional:
    dns:
       - 8.8.8.8
       - 1.1.1.1