services:
  node1:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.5
    container_name: gensyn-test1

    # 4 environment variables, each on its own line:
    environment:
      - P2P_PORT=38331
      - CPU_ONLY=1

    # mount JSON keys and persistent identity
    volumes:
      - "./data/node1/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"
      - "./identities/node1/swarm.pem:/opt/rl-swarm/swarm.pem"
      - "./run_rl_swarm_json_save.sh:/opt/rl-swarm/run_rl_swarm.sh:ro"

    ports:
      - "38331:38331"

    restart: on-failure

    # Pin and limit to the first 20 cores
    cpuset: "0-19"
    deploy:
      resources:
        limits:
          cpus: "20.0"


    # optional:
    dns:
       - 8.8.8.8
       - 1.1.1.1


  node2:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.5
    container_name: gensyn-test2
    environment:
      - P2P_PORT=38332       # ← bind inside container to 38332
      - CPU_ONLY=1
    volumes:
      - "./data/node2/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"
      - "./identities/node2/swarm.pem:/opt/rl-swarm/swarm.pem"
      - "./run_rl_swarm_json_save.sh:/opt/rl-swarm/run_rl_swarm.sh:ro"
    ports:
      - "38332:38332"        # ← expose 38332 on the host
    restart: on-failure
    cpuset: "20-39"          # ← next block of 20 cores
    deploy:
      resources:
        limits:
          cpus: "20.0"
     # optional:
    dns:
       - 8.8.8.8
       - 1.1.1.1

  node3:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.5
    container_name: gensyn-test3

    environment:
      - P2P_PORT=38333
      - CPU_ONLY=1

    volumes:
      - "./data/node3/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"
      - "./identities/node3/swarm.pem:/opt/rl-swarm/swarm.pem"
      - "./run_rl_swarm_json_save.sh:/opt/rl-swarm/run_rl_swarm.sh:ro"

    ports:
      - "38333:38333"

    restart: on-failure
    cpuset: "40-59"            # adjust your core range
    deploy:
      resources:
        limits:
          cpus: "20.0"
    
      # optional:
    dns:
       - 8.8.8.8
       - 1.1.1.1


  node4:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.5
    container_name: gensyn-test4

    environment:
      - P2P_PORT=38334
      - CPU_ONLY=1

    volumes:
      - "./data/node4/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"
      - "./identities/node4/swarm.pem:/opt/rl-swarm/swarm.pem"
      - "./run_rl_swarm_json_save.sh:/opt/rl-swarm/run_rl_swarm.sh:ro"

    ports:
      - "38334:38334"

    restart: on-failure
    cpuset: "60-79"
    deploy:
      resources:
        limits:
          cpus: "20.0"

    
       # optional:
    dns:
       - 8.8.8.8
       - 1.1.1.1