services:
  node1:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.1
    container_name: gensyn-test1

    # 4 environment variables, each on its own line:
    environment:
      - P2P_PORT=38331
      - CPU_ONLY=1

    # mount JSON keys and persistent identity
    volumes:
      - "./data/node1/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"
      - "./identities/node1/swarm.pem:/opt/rl-swarm/swarm.pem"

    ports:
      - "38331:38331"

    restart: on-failure

    # Pin and limit to the first 20 cores
    cpuset: "0-19"
    deploy:
      resources:
        limits:
          cpus: "20.0"


    # optional:
    dns:
       - 8.8.8.8
       - 1.1.1.1