# docker-compose.yml
#
# Single-node test compose file.
# Each container gets 20 vCPU and 20 GiB RAM limits.

version: "3.9"

services:
  node1:
    image: ghcr.io/ashishki/gensyn-node:cpu-2.7.0   # ← after you push
    container_name: gensyn-test1

    environment:
      P2P_PORT: 38331
      CPU_ONLY: "1"          # force the CPU branch

    # mount only keys
    volumes:
      - "./data/node1/modal-login/temp-data:/opt/rl-swarm/modal-login/temp-data"

    ports:
      - "38331:38331"
      - "13001:8000"         # UI (optional)

    deploy:
      resources:
        limits:
          cpus: "20.0"
          memory: 20g

